### ISSUE TITLE
[BUG] - Protocol error, got "H" as reply type byte. Please report this.

### ISSUE THREAD

**Issue by allerallegro** [cweijan/vscode-mysql#589]
While trying to connect to redis (tls) I got this message: "Protocol error, got "H" as reply type byte. Please report this."
I tested the connection via openssl and it works.
![image](https://user-images.githubusercontent.com/31351604/169546140-73c07f23-1b88-4a6a-96d2-eb25e1f97f8f.png)

- OS: Windows 11 (client) / Redis server docker image redis:bullseye
- Database Type: Redis

**Comment by cweijan** [comment]
I'm sorry I didn't encounter this error, I built a redis that supports ssl, and the extension can connect normally.
Showing me your redis connection configuration might help me with this.

**Comment by allerallegro** [comment]
I've tried several ways to connect, but to no avail. Testing via openssl, I was able to connect and run the commands.

![image](https://user-images.githubusercontent.com/31351604/169822542-326e50a6-b0a0-4ec2-8dca-2cdfe3cef09f.png)
![image](https://user-images.githubusercontent.com/31351604/169824414-41321f96-eab7-465c-af3b-b6f5b99bcb60.png)
![image](https://user-images.githubusercontent.com/31351604/169823315-76e84d87-7c5b-49ff-bc41-57f5d1a855ff.png)

**Comment by cweijan** [comment]
I searched for this problem, it seems to be caused by your redis service config.
https://blog.krybot.com/a?ID=9200ed94-975e-4f3f-a795-64e10e78f449
Also, you need to verify that you can connect via redis-cli instead of openssl, like this `redis-cli -h <host> -p <port> --tls`.

**Comment by allerallegro** [comment]
I tested it with the redis client and was able to access it.
![image](https://user-images.githubusercontent.com/31351604/169921783-d0e44e8b-70e5-4d65-8982-73bd2653869c.png)

**Comment by cweijan** [comment]
Thank you for your patience. But the current information can't solve this problem. May I ask whether your redis service uses cloud service or builds it yourself, I need to build an environment like yours to solve this problem.

**Comment by allerallegro** [comment]
I'm using 'traefik' behind the redis server.
I put the environment configuration files below.

**traefik**
docker-compose.yml 

```
version: "3.9"
services:
  traefik:
    image: traefik
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./dynamic_config.yml:/config.yml:ro
      - ./certs:/etc/certs:ro
      - ./config.yml:/etc/traefik/config.yml
      - ./logs:/var/log/traefik
    
    networks:
      - web

    ports:
      - 8080:8080
      - 80:80
      - 443:443
      - 5701:5701
      - 6379:6379
      - 6380:6380
    restart: always
    container_name: traefik
networks: 
  web:
```
traefik.yml
```
## STATIC CONFIGURATION
api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

  rabbit:
    address: ":5672/tcp"

  redis:
    address: ":6379/tcp"

  redis-secure: 
    address: ":6380/tcp"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.xxx.com.br`)"
  file:
    filename: /etc/traefik/config.yml

accessLog: 
  filePath: "/var/log/traefik/access.log"
  format: json
```

config.yml
```
tls:
  certificates:
      - certFile: /etc/certs/xxx.com.br.cert.pem
        keyFile: /etc/certs/xx.com.br.key.pem
      - certFile: /etc/certs/ca.crt
        keyFile: /etc/certs/xx.com.br.key
  stores:
    default: {}
  options:
    default:
      minVersion: VersionTLS12
      alpnProtocols: 
        - "http/1.1"
        - "http/2.0"
    # mintls13:
    #   minVersion: VersionTLS13
```


**redis**
docker-compose.yml
```
version: "3.9"
services:
  redis:
    image: redis:bullseye
    command: redis-server /etc/redis/redis.conf --requirepass sadadasdasdasdas
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traeffik_web
      - traefik.tcp.routers.redis.rule=HostSNI(`xx.com.br`)
      - traefik.tcp.routers.redis.entrypoints=redis-secure
      - traefik.tcp.routers.redis.tls=true
      - "traefik.tcp.routers.redis.tls.domains.0.main=xx.com.br"
      - "traefik.tcp.routers.redis.tls.passthrough=true"
      - traefik.tcp.services.redis.loadbalancer.server.port=6380
    networks:
      - web
      - default
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - ./certs:/etc/certs

networks:
  default:
  web:
    name: traeffik_web
    external: true
```

redis.conf
```
bind * -::* 
protected-mode no
port 6379
tcp-backlog 511
timeout 0
tcp-keepalive 300
tls-port 6380
tls-cert-file /etc/certs/xx.com.br.crt
tls-key-file /etc/certs/xx.com.br.key
tls-ca-cert-file /etc/certs/ca.crt
tls-auth-clients no
daemonize no
pidfile /var/run/redis_6379.pid
loglevel notice
logfile ""
databases 16
always-show-logo no
set-proc-title yes
proc-title-template "{title} {listen-addr} {server-mode}"
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb
rdb-del-sync-files no
dir ./
replica-serve-stale-data yes
replica-read-only yes
repl-diskless-sync yes
repl-diskless-sync-delay 5
repl-diskless-sync-max-replicas 0
repl-diskless-load disabled
repl-disable-tcp-nodelay no
replica-priority 100
acllog-max-len 128
lazyfree-lazy-eviction no
lazyfree-lazy-expire no
lazyfree-lazy-server-del no
replica-lazy-flush no
lazyfree-lazy-user-del no
lazyfree-lazy-user-flush no
oom-score-adj no
oom-score-adj-values 0 200 800
disable-thp yes
appendonly no
appendfilename "appendonly.aof"
appenddirname "appendonlydir"
appendfsync everysec
no-appendfsync-on-rewrite no
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb
aof-load-truncated yes
aof-use-rdb-preamble yes
aof-timestamp-enabled no 
slowlog-log-slower-than 10000
slowlog-max-len 128
latency-monitor-threshold 0
notify-keyspace-events ""
hash-max-listpack-entries 512
hash-max-listpack-value 64
list-max-listpack-size -2
list-compress-depth 0
set-max-intset-entries 512
zset-max-listpack-entries 128
zset-max-listpack-value 64
hll-sparse-max-bytes 3000
stream-node-max-bytes 4096
stream-node-max-entries 100
activerehashing yes
client-output-buffer-limit normal 0 0 0
client-output-buffer-limit replica 256mb 64mb 60
client-output-buffer-limit pubsub 32mb 8mb 60
hz 10
dynamic-hz yes
aof-rewrite-incremental-fsync yes
rdb-save-incremental-fsync yes
jemalloc-bg-thread yes
```
